# Generated by Django 6.0.2 on 2026-02-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userfile', '0004_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
